on: [pull_request]

jobs:
  check-dependency-availability:
    name: Check fresh compile and package of threddsIso project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build and test with Maven
        run: mvn clean package

