on: [pull_request]

jobs:
  tests:
    name: threddsIso Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 17 and 21
        distribution: [zulu, adopt]
        java: [ 17, 21 ]
        profile: [ dev, prod ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup java ${{ matrix.java }}i (${{ matrix.distribution }})
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and test with Maven
        run: mvn clean verify -DskipTests=false -P ${{ matrix.profile }}

